default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: <%= ENV.fetch('POSTGRES_USER') { 'rails_rspec' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { '123' } %>

development:
  <<: *default
  database: rails_rspec_development


test:
  <<: *default
  database: rails_rspec_test
