development:
  adapter: postgresql
  encoding: unicode
  database: rails_rspec_development
  pool: 5
  username: rails_rspec
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: rails_rspec_test
  pool: 5
  username: rails_rspec
  password: 123
