development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: rails_rspec_development
  pool: 5
  username: rails_rspec
  password: 123

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: rails_rspec_test
  pool: 5
  username: <%= ENV.fetch('POSTGRES_USER') { 'rails_rspec' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { '123' } %>
