name: Specs

on: push

jobs:
  specs:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: rails_rspec
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rails_rspec_test

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.1
      - name: Install dependencies
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: bundle install
      - name: Database setup
        run: |
          rake db:create
          rake db:migrate
        env:
          RAILS_ENV: test
      - name: Run linter
        run: rspec
